[package]
name = "heuristics"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3      # make it 3 fast

[dependencies]
priority-queue = "2.3.1"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
smallvec = "2.0.0-alpha.11"

